// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomePageRoute from "@/app/page.info";
import * as DatasetUploadRoute from "@/app/dataset/[datasetId]/upload/page.info";

export const HomePage = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomePageRoute.Route
  }
);
export const DatasetUpload = makeRoute(
  "/dataset/[datasetId]/upload",
  {
    ...defaultInfo,
    ...DatasetUploadRoute.Route
  }
);

