// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomePageRoute from "@/app/page.info";
import * as DatasetListRoute from "@/app/datasets/page.info";
import * as DatasetDetailRoute from "@/app/datasets/[datasetId]/page.info";
import * as DataDetailsRoute from "@/app/datasets/[datasetId]/data/[dataId]/page.info";
import * as NewDataRoute from "@/app/datasets/[datasetId]/data/new/page.info";
import * as NewDatasetRoute from "@/app/datasets/new/page.info";

export const HomePage = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomePageRoute.Route
  }
);
export const DatasetList = makeRoute(
  "/datasets",
  {
    ...defaultInfo,
    ...DatasetListRoute.Route
  }
);
export const DatasetDetail = makeRoute(
  "/datasets/[datasetId]",
  {
    ...defaultInfo,
    ...DatasetDetailRoute.Route
  }
);
export const DataDetails = makeRoute(
  "/datasets/[datasetId]/data/[dataId]",
  {
    ...defaultInfo,
    ...DataDetailsRoute.Route
  }
);
export const NewData = makeRoute(
  "/datasets/[datasetId]/data/new",
  {
    ...defaultInfo,
    ...NewDataRoute.Route
  }
);
export const NewDataset = makeRoute(
  "/datasets/new",
  {
    ...defaultInfo,
    ...NewDatasetRoute.Route
  }
);

