#!/usr/bin/env bash

function change_user_and_group_to_sail() {
    local dir="$1"
    local recursive="${2:-false}"
    current_user="$(stat -c "%U" "$dir")"
    current_group="$(stat -c "%G" "$dir")"
    if [ "$current_user" != "sail" ] || [ "$current_group" != "sail" ]; then
        if [ "$recursive" = "true" ]; then
            chown -R sail:sail "$dir"
        else
            chown sail:sail "$dir"
        fi
    fi
}

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
    change_user_and_group_to_sail /rnadetector
    change_user_and_group_to_sail /rnadetector/miniforge true
    change_user_and_group_to_sail /rnadetector/scripts true
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
